import{S as q,a as y,i as g}from"./assets/vendor-eacb4d5c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const b="41949985-8da78252305a4c2e980ced1f3",P=document.querySelector(".search-form"),L=document.querySelector(".gallery"),w=new q(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".loader"),h=document.querySelector(".load-more");let l=1,n=0,c="",i=0;f.style.display="none";h.classList.remove("visible");P.addEventListener("submit",x);h.addEventListener("click",C);async function x(e){if(e.preventDefault(),c=e.target.querySelector(".search-input").value.trim(),!c){F("Please enter image name!");return}M(),E(),m();try{const t=await y.get("https://pixabay.com/api/",{params:{key:b,per_page:40,safesearch:!0,page:l,orientation:"horizontal",image_type:"photo",q:c}});d();const s=t.data;if(s.hits.length===0){p("Sorry, there are no images matching your search query. Please try again!");return}n=s.totalHits,i=s.hits.length,v(s.hits),w.refresh(),S(`We found ${n} images.`),n>40&&I()}catch(t){console.error("Error fetching images:",t),d(),p("Failed to fetch images. Please try again later.")}}function v(e){const t=document.createDocumentFragment();e.forEach(s=>{const a=$(s);t.appendChild(a)}),L.appendChild(t)}function $(e){const t=document.createElement("div");return t.classList.add("card"),t.innerHTML=`
    <a class="gallery-link" href="${e.largeImageURL}">
    <img class="card-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
    </a>
    <div class="card-info">
      <p class="card-text"><b>Likes:</b> ${e.likes}</p>
      <p class="card-text"><b>Views:</b> ${e.views}</p>
      <p class="card-text"><b>Comments:</b> ${e.comments}</p>
      <p class="card-text"><b>Downloads:</b> ${e.downloads}</p>
    </div>
  `,t}function M(){L.innerHTML="",l=1,m()}async function C(){E(),m();try{const e=await y.get("https://pixabay.com/api/",{params:{key:b,safesearch:!0,per_page:40,page:l+1,orientation:"horizontal",image_type:"photo",q:c}});d();const t=e.data;if(t.hits.length===0)return;l++,i+t.hits.length>n&&(t.hits=t.hits.slice(0,n-i)),i+=t.hits.length,v(t.hits),w.refresh(),i>=n?(m(),S("We're sorry, but you've reached the end of search results.")):I();const s=document.querySelectorAll(".card"),a=Array.from(s).slice(-40);a.length>0&&a[0].scrollIntoView({behavior:"smooth",block:"start"})}catch(e){console.error("Error fetching more images:",e),d(),p("Failed to fetch more images. Please try again later.")}}const E=()=>{f.style.display="block"},d=()=>{f.style.display="none"},I=()=>{h.style.display="block"},m=()=>{h.style.display="none"},F=e=>{g.warning({title:"Warning!",message:e,position:"topRight"})},p=e=>{g.error({message:e,position:"topRight"})},S=e=>{g.info({message:e,position:"topRight"})};
//# sourceMappingURL=commonHelpers.js.map
